import pickle
import os

class Tokenizer:
    """
    Simple character-level tokenizer that wraps the meta.pkl
    generated by prepare.py for nanoGPT.
    """

    def __init__(self, data_dir="data/music_char_nanogpt"):
        meta_path = os.path.join(data_dir, "meta.pkl")
        if not os.path.exists(meta_path):
            raise FileNotFoundError(f"meta.pkl not found at: {meta_path}")

        with open(meta_path, "rb") as f:
            meta = pickle.load(f)

        self.stoi = meta["stoi"]
        self.itos = meta["itos"]
        self.vocab_size = meta["vocab_size"]

    def encode(self, s):
        """Convert string → list of token IDs"""
        return [self.stoi[c] for c in s if c in self.stoi]

    def decode(self, tokens):
        """Convert list of token IDs → string"""
        return "".join([self.itos[t] for t in tokens])

